"""add_exam_id_and_pdf_paths_to_tests

Revision ID: e4e5b26f65be
Revises: 145744f1537f
Create Date: 2026-01-18 16:02:42.436850+00:00

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e4e5b26f65be'
down_revision: Union[str, None] = '145744f1537f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tests', sa.Column('exam_id', sa.String(length=10), nullable=True))
    op.add_column('tests', sa.Column('student_pdf_path', sa.String(length=500), nullable=True))
    op.add_column('tests', sa.Column('teacher_pdf_path', sa.String(length=500), nullable=True))
    op.create_index(op.f('ix_tests_exam_id'), 'tests', ['exam_id'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_tests_exam_id'), table_name='tests')
    op.drop_column('tests', 'teacher_pdf_path')
    op.drop_column('tests', 'student_pdf_path')
    op.drop_column('tests', 'exam_id')
    # ### end Alembic commands ###
