"""add_problem_bank_table

Revision ID: 145744f1537f
Revises: 
Create Date: 2026-01-18 10:15:11.585363+00:00

"""
from typing import Sequence, Union


# revision identifiers, used by Alembic.
revision: str = '145744f1537f'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
